#!/usr/bin/env bash

abs_rosenthal_dir="$(dirname "$(realpath "$0")")"

GUILE_LOAD_PATH="${abs_rosenthal_dir}${GUILE_LOAD_PATH:+:}${GUILE_LOAD_PATH}"
GUIX_PACKAGE_PATH="${abs_rosenthal_dir}${GUIX_PACKAGE_PATH:+:}${GUIX_PACKAGE_PATH}"

export GUILE_LOAD_PATH GUIX_PACKAGE_PATH

exec "$@"
