# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

background-color=#D2DEE9E0
border-color=#D2DEE9
text-color=#13181B
border-radius=5
font=monospace 11
