# SPDX-FileCopyrightText: 2025 Hilton Chain <hako@ultrarare.space>
#
# SPDX-License-Identifier: CC0-1.0

font=monospace 11
text-color=#13181B
background-color=#D2DEE9E0
border-size=1
border-color=#B3C6D3
border-radius=5
